#![no_std]

mod merkle;

use soroban_sdk::{contract, contractimpl, contracttype, Address, BytesN, Env, Symbol, Vec};

const TOKEN: Symbol = Symbol::new("token");
const NEXT_INDEX: Symbol = Symbol::new("next_idx");
const MERKLE_ROOT: Symbol = Symbol::new("merkle_root");
const COMMITMENTS: Symbol = Symbol::new("commitments");
const SPENT: Symbol = Symbol::new("spent_null");

#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct NullifierWrapper {
    pub val: BytesN<32>,
}

#[contract]
pub struct ShieldedPayment;

#[contractimpl]
impl ShieldedPayment {
    pub fn initialize(env: Env, token: Address) {
        env.storage().instance().set(&TOKEN, &token);
        env.storage().instance().set(&NEXT_INDEX, &0u64);
        // empty root
        env.storage()
            .instance()
            .set(&MERKLE_ROOT, &BytesN::from_array(&env, &[0u8; 32]));
    }

    pub fn deposit(env: Env, from: Address, commitment: BytesN<32>, amount: i128) {
        from.require_auth();

        let token: Address = env.storage().instance().get(&TOKEN).unwrap();

        // Transfer tokens to contract
        let client = soroban_sdk::token::Client::new(&env, &token);
        client.transfer(&from, &env.current_contract_address(), &amount);

        // Append commitment to tree
        let mut commitments: Vec<BytesN<32>> = env
            .storage()
            .instance()
            .get(&COMMITMENTS)
            .unwrap_or(Vec::new(&env));
        commitments.push_back(commitment.clone());
        env.storage().instance().set(&COMMITMENTS, &commitments);

        // Recompute Merkle root
        let root = merkle::compute_root(&env, &commitments);
        env.storage().instance().set(&MERKLE_ROOT, &root);

        // Increment count
        let count: u64 = env.storage().instance().get(&NEXT_INDEX).unwrap();
        env.storage()
            .instance()
            .set(&NEXT_INDEX, &(count + 1));

        env.events().publish(("deposit",), (commitment, amount));
    }

    /// Withdraw from the pool.
    ///
    /// The user must provide:
    /// - nullifier: unique hash that prevents double-spending
    /// - recipient: who receives the tokens
    /// - amount: amount to withdraw
    /// - merkle_proof: sibling hashes along the path
    /// - path_index: leaf index encoded as 4 bytes
    /// - commitment: the original commitment (to verify against tree)
    ///
    /// The ZK proof (generated by Noir) ensures the user knows the secret
    /// WITHOUT revealing which leaf is theirs. The contract then verifies
    /// the Merkle proof on-chain.
    pub fn withdraw(
        env: Env,
        nullifier: BytesN<32>,
        recipient: Address,
        amount: i128,
        merkle_proof: Vec<BytesN<32>>,
        path_index: BytesN<4>,
        commitment: BytesN<32>,
    ) {
        recipient.require_auth();

        // Check nullifier not spent
        let spent: Vec<NullifierWrapper> = env
            .storage()
            .instance()
            .get(&SPENT)
            .unwrap_or(Vec::new(&env));
        for n in spent.iter() {
            if n.val == nullifier {
                panic!("nullifier already spent");
            }
        }

        // Verify Merkle proof
        let root: BytesN<32> = env.storage().instance().get(&MERKLE_ROOT).unwrap();
        if !merkle::verify(&env, &commitment, &path_index, &merkle_proof, &root) {
            panic!("merkle proof invalid");
        }

        // Mark nullifier as spent
        let mut spent = spent;
        spent.push_back(NullifierWrapper {
            val: nullifier.clone(),
        });
        env.storage().instance().set(&SPENT, &spent);

        // Transfer tokens
        let token: Address = env.storage().instance().get(&TOKEN).unwrap();
        let client = soroban_sdk::token::Client::new(&env, &token);
        client.transfer(&env.current_contract_address(), &recipient, &amount);

        env.events()
            .publish(("withdraw",), (nullifier, recipient, amount));
    }

    /// Store a verifying key for a Groth16 verifier (optional, for full on-chain ZK).
    pub fn set_verifying_key(env: Env, vk: Vec<u8>) {
        // In a full implementation, this stores the Groth16 VK
        // and the withdraw function additionally verifies the ZK proof
        env.storage().instance().set(&Symbol::new(&env, "vk"), &vk);
    }

    pub fn get_merkle_root(env: Env) -> BytesN<32> {
        env.storage()
            .instance()
            .get(&MERKLE_ROOT)
            .unwrap_or(BytesN::from_array(&env, &[0u8; 32]))
    }

    pub fn get_commitment_count(env: Env) -> u64 {
        env.storage()
            .instance()
            .get(&NEXT_INDEX)
            .unwrap_or(0u64)
    }

    pub fn is_nullifier_spent(env: Env, nullifier: BytesN<32>) -> bool {
        let spent: Vec<NullifierWrapper> = env
            .storage()
            .instance()
            .get(&SPENT)
            .unwrap_or(Vec::new(&env));
        for n in spent.iter() {
            if n.val == nullifier {
                return true;
            }
        }
        false
    }
}
